### PR TITLE
Fix organization fetching

### LINKED ISSUE #54: Error on Multiple Organizations after update to new Management SDK
```
lib/contentful/bootstrap/commands/create_space.rb:76:in `organizations': undefined method `get_http' for #<Contentful::Bootstrap::Management:0x007fdcc186a268> (NoMethodError)
```

### PR DESCRIPTION
**Pull request by dlitvakb**
Fixes #54

### CODE REVIEW

File: lib/contentful/bootstrap/commands/create_space.rb [hunk 1]
```diff
@@ -48,6 +48,7 @@ def fetch_space
               name: @space
             }
             options[:organization_id] = @token.read_organization_id unless @token.read_organization_id.nil?
+            management_client_init
```
Comment (mariobodemann) [inline lib/contentful/bootstrap/commands/create_space.rb]: In https://github.com/contentful/contentful-bootstrap.rb/pull/55/files#diff-42edb6f486ee67a681d11b974db3cef0R75 you assign `client = management_client_init` shouldn't you do similar things here?

Comment (dlitvakb) [inline lib/contentful/bootstrap/commands/create_space.rb]: `management_client_init` does `@client ||= ...` so basically they are equivalent, but at the point this invocation is made... there were cases (when `trigger_oauth` was false) in which the client would not be present, therefore this invocation is required... i could remove the assignment in the other instance of this invocation... so it's not confusing, but they are completely equivalent

Comment (mariobodemann) [inline lib/contentful/bootstrap/commands/create_space.rb]: Okay, since they are the same, let's keep it for a different change then....
